### ISSUE TITLE
If you'd like to replace ZeroSSL with Let's Encrypt

### ISSUE THREAD

**Issue by keaising** [Menci/acme#5]
According to acme.sh's documents, if you'd like to [replace ZeroSSL with Let's Encrypt](https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL), you should run a **STANDALONE** command 
```bash
acme.sh --set-default-ca --server letsencrypt
```
This command will append a line into your `~/.acme.sh/account.conf`:
```bash
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
```
So if you want to replace ZeroSSL with Let's Encrypt in this Github Actions, you'd better append the line to your local `account.conf` and regenerate the `account-tar` file with `tar cz ca account.conf | base64 -w0` running in your `~/.acme.sh`

Please don't append `--set-default-ca --server letsencrypt` into `arguments` or `arguments-file` in this Github Actions parameter, if you do that, the `acme.sh --issue` in this Github Action will never run because it was masked by `--set-default-ca --server letsencrypt`

如果你需要在这个 Github Action 里使用 Let's Encrypt 的话，需要先在本地 acme.sh 里执行 
```bash
acme.sh --set-default-ca --server letsencrypt
```
然后重新生成 `account-tar` 文件
如果直接将 `--set-default-ca --server letsencrypt` 添加到 Github Actions 的 `arguments` 参数里的话，原本应该执行的 `acme.sh --issue` 就会被覆盖，导致没有执行 issue certifications 的步骤，后续也会报错

**Comment by keaising** [comment]
@Menci 或许我们可以增加一个变量来允许用户通过设置不同的参数切换自己要用的 CA。如果你觉得这个方案可行的话，我可以来贡献这部分代码

**Comment by Menci** [comment]
在 options 里加上 --server 参数就可以，然后向 ca 注册的账户是保存在 account tar 里的，其实我自己用的就是 gts

**Comment by keaising** [comment]
棒！
